### ISSUE TITLE
[community] Would you like to publish the crate?

### ISSUE THREAD

**Issue by saona-raimundo** [lapce/floem#163]
I see that the crate is still not published in crates.io, and therefore it is also not part of https://areweguiyet.com/

Would you consider publishing it to keep track of your approach in the GUI in Rust landscape?

**Comment by panekj** [comment]
The crate is not published since it's still in heavy development and the API is not stable

**Comment by dominikwilkowski** [comment]
FYI we are using it like this and I like keeping track of merged PRs and opt into changes myself

```toml
[dependencies]
floem = { git = "https://github.com/lapce/floem.git", rev = "46d9a784cca621402d1a6eaa9c54d00352c7520d" }
im = "15.1.0"
```
